### ISSUE TITLE
input.profiles -> input.gacode

### ISSUE THREAD

**Issue by smithsp** [gafusion/doc#2]
@jcandy @bellie Please update the documentation in this repo for input.profiles(.geo) vs input.gacode.
```
~/gafusion_doc/html 99 : git grep -l input.profiles
src/cgyro.rst
src/cgyro/cgyro_list.rst
src/index.rst
src/input_profiles.rst
src/neo.rst
src/neo/neo_list.rst
src/tgyro.rst
src/tgyro/tgyro_list.rst
src/tgyro/tgyro_table.rst
```

**Comment by jcandy** [comment]
I'll get to it eventually.  The queue is very long now.

**Comment by smithsp** [comment]
As long as it's in the queue :-)

**Comment by jcandy** [comment]
I already got a start on it weeks ago:

http://gafusion.github.io/doc/input_gacode.html

I think some of the content you flagged is just being kept there for reference purposes as new content is added.

**Comment by smithsp** [comment]
The specific variables that prompted the `git grep` were actually NEO inputs: `EQUILIBRIUM_MODEL` and `PROFILE_EQUILIBRIUM_MODEL`.
